name: Bug Report
description: Report a bug in Starkclaw
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please fill out the sections below so we can reproduce and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Open the app
        2. Navigate to ...
        3. Tap ...
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Mobile app
        - Cairo contracts
        - Agent runtime
        - Scripts / CI
        - Other
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, device, Expo SDK version, Scarb version, etc.
      placeholder: "iOS 18, iPhone 15 Pro, Expo SDK 54"
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or attach screenshots.
