name: Feature Request
description: Propose a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the feature you'd like. Include acceptance criteria so an agent or contributor can implement it independently.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Why is it needed?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Be as concrete as possible.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this is done? List verifiable checks.
      placeholder: |
        - [ ] Feature X works when ...
        - [ ] `./scripts/check` passes
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Mobile app
        - Cairo contracts
        - Agent runtime
        - Scripts / CI
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered and why this one is better.
